################################################################################
# Automatically-generated file. Do not edit!
################################################################################

O_SRCS := 
CPP_SRCS := 
C_UPPER_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
OBJ_SRCS := 
ASM_SRCS := 
CXX_SRCS := 
C++_SRCS := 
CC_SRCS := 
C++_DEPS := 
OBJS := 
C_DEPS := 
CC_DEPS := 
CPP_DEPS := 
EXECUTABLES := 
CXX_DEPS := 
C_UPPER_DEPS := 

# Every subdirectory with source files must be described here
SUBDIRS := \
uip/utility \
uip \
sdfatlib20130629/extra/SdFatTestSuite \
network_enc28j60 \
glcd \
glcd/examples/clockFace \
glcd/examples/GLCD_BigDemo \
etherShield_v10/etherShield \
etherShield_v10/ETHER_28J60 \
arduino_uip/utility \
arduino_uip \
WaveHC \
UsbKeyboard \
UartBridge_SC16IS750 \
UTFT4ArduCAM_SPI \
USB_Host_Shield \
USB_Host_Shield/examples/HID/le3dp \
USB_Host_Shield/examples/HID/USBHIDJoystick \
TouchScreen \
Tools \
Tlc5940 \
TimerOne \
TimerCounter \
TFTLCD/examples/tftpaint_shield \
TFTLCD \
Sparkfun6DOF \
SerialSRAM \
Sensirion \
SdFat \
SD_SPI/utility \
SD_SPI \
SDFatFs \
SDFatFs/mmc_old \
SDFatFs/ffsample/win32/option \
SDFatFs/ffsample/win32 \
SDFatFs/ffsample/v850es \
SDFatFs/ffsample/sh7262/fftest \
SDFatFs/ffsample/sh7262/fftest/option \
SDFatFs/ffsample/rx600/ff_rx62n \
SDFatFs/ffsample/pic24 \
SDFatFs/ffsample/lpc23xx \
SDFatFs/ffsample/lpc23xx/tools \
SDFatFs/ffsample/lpc23xx/option \
SDFatFs/ffsample/lpc176x \
SDFatFs/ffsample/h8/h8_mmc \
SDFatFs/ffsample/generic \
SDFatFs/ffsample/fm3 \
SDFatFs/ffsample/avrfp \
SDFatFs/ffsample/avr \
SDFatFs/ffsample/avr/unicode \
SDFatFs/ff9b/src/option \
SDFatFs/ff9b/src \
SDFatFs/ff9b/doc/img \
SDFatFs/FatFs \
SCP1000D01 \
Roomba500 \
Roomba \
RTC_I2C \
RFID_StrongLink_UART \
RFID_StrongLink \
RFID_RCS620S/RFID_PaSoRi \
RFID_RCS620S \
RFID_PN532 \
RFID_ISO14443 \
Pololu/PololuWheelEncoders \
Pololu/PololuQTRSensors \
Pololu/Pololu3pi \
Pololu/OrangutanResources \
Pololu/OrangutanPushbuttons \
Pololu/OrangutanMotors \
Pololu/OrangutanLEDs \
Pololu/OrangutanLCD \
Pololu/OrangutanDigital \
Pololu/OrangutanBuzzer \
Pololu/OrangutanAnalog \
OneWireMaster \
OneWire2/examples \
OneWire2 \
OneWire \
OV7670 \
NewSoftSerial \
MindSet/mdt/tgcd/win32 \
MindSet/mdt/tg \
MindSet \
MCP23Sxx \
MCP230xx \
KeyMatrix \
HMC5843 \
HC595 \
GPS \
GLCD_ST7565 \
FreeRTOS_AVR/utility \
FreeRTOS_AVR \
FeliCaPlug \
Fat16 \
Ethernet_W5100/utility \
Ethernet_W5100 \
Ethernet/utility \
Ethernet \
Digital6DOF \
DataFlash_SPI \
DES_OUTE \
ColorLCDShield \
ChibiOS/utility \
ChibiOS/SdFat \
ChibiOS \
ChibiOS/BufferedWriter \
ChLCD_SoftwareSerial \
ChLCD_ST7032i \
ChLCD_MCP230xx \
ChLCD_HC595 \
CapacitiveSense \
CameraC328R \
BMP085 \
BMP085/ATmega328 \
Arduino_hardware_libraries/Wire/utility \
Arduino_hardware_libraries/Wire \
Arduino_hardware_libraries/WiFi/utility \
Arduino_hardware_libraries/WiFi \
Arduino_hardware_libraries/TFT/utility \
Arduino_hardware_libraries/TFT \
Arduino_hardware_libraries/Stepper \
Arduino_hardware_libraries/SoftwareSerial \
Arduino_hardware_libraries/Servo \
Arduino_hardware_libraries/SPI \
Arduino_hardware_libraries/SD/utility \
Arduino_hardware_libraries/SD \
Arduino_hardware_libraries/Robot_Motor \
Arduino_hardware_libraries/Robot_Control/utility \
Arduino_hardware_libraries/Robot_Control \
Arduino_hardware_libraries/LiquidCrystal \
Arduino_hardware_libraries/GSM \
Arduino_hardware_libraries/Firmata \
Arduino_hardware_libraries/Ethernet/utility \
Arduino_hardware_libraries/Ethernet \
Arduino_hardware_libraries/Esplora \
Arduino_hardware_libraries/EEPROM \
Arduino_hardware_cores/robot \
Arduino_hardware_cores/arduino \
Arduino_hardware_cores/arduino/avr-libc \
ArduCAM \
Adafruit_PCD8544_Nokia_LCD \
Adafruit_NeoPixel \
Adafruit_LED_Backpack \
Adafruit_GFX_modified \
Adafruit_CC3000/utility \
Adafruit_CC3000 \
AP_GPS \
APM_Compass \
AFMotor \
AES128 \
ADC_MCP320X \

